name: topmed-django-dev
dependencies:
- django=1.8.4=py35_0
- mysql-connector-python=2.0.3=py35_0
- openssl=1.0.2e=0
- pip=8.0.1=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=19.4=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - django-ordered-model==1.1.0
  - django-tables2==1.1.0
  - six==1.10.0
