# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 23:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_remove_taggedtrait_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCCReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Needs study followup'), (1, 'Confirmed')])),
                ('comment', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagged_trait', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcc_review', to='tags.TaggedTrait')),
            ],
            options={
                'verbose_name': 'dcc review',
            },
        ),
    ]
