# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trait_browser', '0011_remove_old_dbgap_link_fields'),
        ('tags', '0004_taggedtrait_add_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='traits',
        ),
        migrations.AddField(
            model_name='tag',
            name='all_traits',
            field=models.ManyToManyField(related_name='all_tags', through='tags.TaggedTrait', to='trait_browser.SourceTrait'),
        ),
        migrations.AlterField(
            model_name='taggedtrait',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_taggedtraits', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='taggedtrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_taggedtraits', to='trait_browser.SourceTrait'),
        ),
    ]
