# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_dccdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedtrait',
            name='previous_tagged_trait',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_tagged_trait', to='tags.TaggedTrait'),
        ),
    ]
