# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait_browser', '0008_global_study_verbose_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcedataset',
            old_name='pht_version_string',
            new_name='full_accession',
        ),
        migrations.RenameField(
            model_name='sourcestudyversion',
            old_name='phs_version_string',
            new_name='full_accession',
        ),
        migrations.RenameField(
            model_name='sourcetrait',
            old_name='dbgap_variable_link',
            new_name='dbgap_link',
        ),
        migrations.RenameField(
            model_name='sourcetrait',
            old_name='variable_accession',
            new_name='full_accession',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='dataset_accession',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='dbgap_dataset_link',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='dbgap_study_link',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='study_accession',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dbgap_latest_version_link',
        ),
        migrations.AddField(
            model_name='sourcedataset',
            name='dbgap_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='sourcestudyversion',
            name='dbgap_link',
            field=models.URLField(default=''),
        ),
    ]
