# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 22:18
from __future__ import unicode_literals

from django.db import migrations


def move_dbgap_link_to_dataset(apps, schema_editor):
    """Copy the SourceTrait.dbgap_dataset_link field to SourceDataset.dbgap_link."""
    SourceDataset = apps.get_model('trait_browser', 'SourceDataset')
    for dataset in SourceDataset.objects.all():
        dataset.dbgap_link = dataset.sourcetrait_set.first().dbgap_dataset_link
        dataset.save()


def remove_dataset_dbgap_link(apps, schema_editor):
    """Remove any data from the dbgap_link field of SourceDatasets."""
    SourceDataset = apps.get_model('trait_browser', 'SourceDataset')
    for dataset in SourceDataset.objects.all():
        dataset.dbgap_link = ''
        dataset.save()


def move_dbgap_link_to_study_version(apps, schema_editor):
    """Copy the SourceTrait.dbgap_study_link field to SourceStudyVersion.dbgap_link."""
    SourceStudyVersion = apps.get_model('trait_browser', 'SourceStudyVersion')
    for ssv in SourceStudyVersion.objects.all():
        ssv.dbgap_link = ssv.sourcedataset_set.first().sourcetrait_set.first().dbgap_study_link
        ssv.save()


def remove_study_version_dbgap_link(apps, schema_editor):
    """Remove any data from the dbgap_link field of SourceStudyVersions."""
    SourceStudyVersion = apps.get_model('trait_browser', 'SourceStudyVersion')
    for ssv in SourceStudyVersion.objects.all():
        ssv.dbgap_link = ''
        ssv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trait_browser', '0009_add_full_accession_and_dbgap_link_fields'),
    ]

    operations = [
        migrations.RunPython(move_dbgap_link_to_dataset, reverse_code=remove_dataset_dbgap_link),
        migrations.RunPython(move_dbgap_link_to_study_version, reverse_code=remove_study_version_dbgap_link),
    ]
