# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait_browser', '0010_move_dbgap_links_from_sourcetrait_to_relevant_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcetrait',
            name='dataset_accession',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='dbgap_dataset_link',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='dbgap_study_link',
        ),
        migrations.RemoveField(
            model_name='sourcetrait',
            name='study_accession',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dbgap_latest_version_link',
        ),
        migrations.AlterField(
            model_name='sourcedataset',
            name='dbgap_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sourcestudyversion',
            name='dbgap_link',
            field=models.URLField(),
        ),
    ]
